services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "3001:3001" 
    depends_on:
      - mongo
    environment:
      PORT: 3001 
      MONGODB_URI: mongodb://root:rootpass@mongo:27017/senior-app?authSource=admin
      JWT_SECRET: ${JWT_SECRET} 

volumes:
  mongo_data: