/**
 * API configuration for the application
 */

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:3001/api/v1';

export const apiConfig = {
  baseURL: API_BASE_URL,
  endpoints: {
    auth: {
      register: '/auth/register',
      login: '/auth/login',
      refresh: '/auth/refresh',
      logout: '/auth/logout',
      me: '/auth/me',
      passwordResetRequest: '/auth/password-reset/request',
      passwordResetConfirm: '/auth/password-reset/confirm',
    },
    groups: '/groups',
    groupById: (groupId) => `/groups/${groupId}`,
    groupMembers: (groupId) => `/groups/${groupId}/members`,
    phases: '/phases',
    phaseById: (phaseId) => `/phases/${phaseId}`,
    submissionDocuments: (submissionId) => `/submissions/${submissionId}/documents`,
    groupCommittee: (groupId) => `/groups/${groupId}/committee`,
    groupStatus: (groupId) => `/groups/${groupId}/status`,
    advisors: '/advisors',
    requests: '/requests',
    requestById: (requestId) => `/requests/${requestId}`,
    requestDecision: (requestId) => `/requests/${requestId}/decision`,
    groupAdvisor: (groupId) => `/groups/${groupId}/advisor`,
    groupDisband: (groupId) => `/groups/${groupId}`,
    userSearch: '/users/search',
    invites: '/invites/deliver',
    groupMyTeam: '/groups/my-team',
    groupMyInvites: '/groups/my-invites',
    groupInvites: (groupId) => `/groups/${groupId}/invites`,
    groupInviteRespond: (inviteId) => `/groups/invites/${inviteId}/respond`,
    phaseSchedule: (phaseId) => `/phases/${phaseId}/schedule`,
    advisorValidation: '/admin/advisor-validation',
    sanitizationExecute: '/admin/sanitization/execute',
    adminAssignStudentGroup: (studentId) => `/admin/students/${studentId}/group`,
    submissions: {
      list: '/submissions',
      byGroup: (groupId) => `/submissions?groupId=${groupId}`,
      byCommittee: (committeeId) => `/submissions?committeeId=${committeeId}`,
      mine: '/submissions/me',
      uploadDocument: (submissionId) => `/submissions/${submissionId}/documents`,
      downloadDocument: (submissionId, documentId) => `/submissions/${submissionId}/documents/${documentId}/download`,
    },
    schedules: '/schedules',
    schedulesActive: '/schedules/active',
    gradingWindow: '/schedules/active?phase=GRADING',
    reviews: '/reviews',
    reviewById: (reviewId) => `/reviews/${reviewId}`,
    reviewComments: (reviewId) => `/reviews/${reviewId}/comments`,
    reviewCommentById: (reviewId, commentId) => `/reviews/${reviewId}/comments/${commentId}`,
    reviewRevisionRequests: (reviewId) => `/reviews/${reviewId}/revision-requests`,
    reviewGrade: (reviewId) => `/reviews/${reviewId}/grade`,
    committees: '/committees',
    committeeById: (committeeId) => `/committees/${committeeId}`,
    committeeJuryMembers: (committeeId) => `/committees/${committeeId}/jury-members`,
    committeeJuryMemberByUser: (committeeId, userId) => `/committees/${committeeId}/jury-members/${userId}`,
    committeeAdvisors: (committeeId) => `/committees/${committeeId}/advisors`,
    committeeAdvisorByUser: (committeeId, advisorUserId) => `/committees/${committeeId}/advisors/${advisorUserId}`,
    committeeGroups: (committeeId) => `/committees/${committeeId}/groups`,
    committeeGroupById: (committeeId, groupId) => `/committees/${committeeId}/groups/${groupId}`,
    committeeAdvisorGradingScope: (committeeId, advisorUserId) => `/committees/${committeeId}/advisors/${advisorUserId}/groups`,
    activityLogs: '/admin/activity',
    adminProfessors: '/auth/admin/professors',
    groupFinalGrade: (groupId) => `/groups/${groupId}/final-grade`,
    studentFinalGrade: (studentId) => `/students/${studentId}/final-grade`,
    groupGradeHistory: (groupId) => `/groups/${groupId}/grade-history`,
    storyPoints: (groupId, sprintId) =>
      `/groups/${groupId}/sprints/${sprintId}/story-points`,
    overrideStoryPoints: (groupId, sprintId) =>
      `/groups/${groupId}/sprints/${sprintId}/story-points/override`,
    deliverables: '/deliverables',
    rubrics: (deliverableId) => `/deliverables/${deliverableId}/rubrics`,
    rubricById: (deliverableId, rubricId) => `/deliverables/${deliverableId}/rubrics/${rubricId}`,
    sprints: '/sprints',
    sprintById: (sprintId) => `/sprints/${sprintId}`,
    deliverableEvaluations: '/deliverable-evaluations',
    committeeGrades: (committeeId) => `/committees/${committeeId}/grades`,
    sprintEvaluations: '/sprint-evaluations',
    githubIntegration: (userId) => `/auth/users/${userId}/integrations/github`,
  },
};

export default apiConfig;
